apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: logrotate

spec:
  selector:
    matchLabels:
      app: logrotate

  template:
    metadata:
      labels:
        app: logrotate

    spec:
      containers:
      - name: logrotate
        image: blacklabelops/logrotate