apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      containers:
      - name: payment-service
        image: payment-service:v1

        ports:
        - containerPort: 8080

        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo:4317"

        - name: PROMETHEUS_ENABLED
          value: "true"