apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: payment-service-monitor
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: payment-service

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s